### ISSUE TITLE
Chunks unloading before loading

### ISSUE THREAD

**Issue by unickorn** [Cosmoverse/BlockData#1]
I have a plugin using this virion where I generate new worlds by copy pasting a folder from somewhere else and changing the level name in the level.dat before actually loading it. I'm not sure if it's related, but my chunks appear to unload before loading, causing BlockData to crash the server like this:
![image](https://user-images.githubusercontent.com/29836508/89379253-22acab00-d6fe-11ea-9faf-91a253d7ae30.png)

Would adding an `isset()` check there be an awful move? Any idea what could be causing this?

**Comment by Muqsit** [comment]
isset() does sound awful but i think that's the only way to go with it :(
